// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCruF5HPDxz5mvaGnnGVzMhYqyP4z3VBdY',
    appId: '1:304244314205:web:2711fcf95b6381a416fdb4',
    messagingSenderId: '304244314205',
    projectId: 'chatapp-62a38',
    authDomain: 'chatapp-62a38.firebaseapp.com',
    storageBucket: 'chatapp-62a38.firebasestorage.app',
    measurementId: 'G-60GZF0T63P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVdaVT4s9zZY1I13AjUrq3BMSTJrjRWkE',
    appId: '1:304244314205:android:15f4f34a183dee6d16fdb4',
    messagingSenderId: '304244314205',
    projectId: 'chatapp-62a38',
    storageBucket: 'chatapp-62a38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChMdZ-OMvukEWijHtMg6DHmtOhF4ZNmP0',
    appId: '1:304244314205:ios:625e5367246da60d16fdb4',
    messagingSenderId: '304244314205',
    projectId: 'chatapp-62a38',
    storageBucket: 'chatapp-62a38.firebasestorage.app',
    iosBundleId: 'com.example.flutterBasic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChMdZ-OMvukEWijHtMg6DHmtOhF4ZNmP0',
    appId: '1:304244314205:ios:625e5367246da60d16fdb4',
    messagingSenderId: '304244314205',
    projectId: 'chatapp-62a38',
    storageBucket: 'chatapp-62a38.firebasestorage.app',
    iosBundleId: 'com.example.flutterBasic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCruF5HPDxz5mvaGnnGVzMhYqyP4z3VBdY',
    appId: '1:304244314205:web:8e2d3bc884911d2e16fdb4',
    messagingSenderId: '304244314205',
    projectId: 'chatapp-62a38',
    authDomain: 'chatapp-62a38.firebaseapp.com',
    storageBucket: 'chatapp-62a38.firebasestorage.app',
    measurementId: 'G-DXTEY09NG1',
  );
}
